### ISSUE TITLE
关于multi2sigle_node问题

### ISSUE THREAD

**Issue by maomao0220** [gloryhry/lidar_ground_filter#2]
您好，看了您的代码，关于multi2sigle.cpp中是不是缺少g_tf_listener的获取？？？如果是的话该怎么做呢？期待您的回复

**Comment by gloryhry** [comment]
[g_tf_listener.reset(new tf::TransformListener());](https://github.com/gloryhry/lidar_ground_filter/blob/db320197360e329441c3f1183ebc2e7e6484eed6/src/multi2single.cpp#L96C2-L96C2)这里用new的tf::TransformListener()重设了g_tf_listener指针
